import { Service, User, UserRole, WalletTransaction, Job } from './types';

// CURRENT_USER will be generated from signup data
export let CURRENT_USER: User = {
  id: 'u1',
  name: 'Student User',
  username: '@student',
  avatar: 'https://picsum.photos/seed/default/200/200',
  role: UserRole.CLIENT,
  rating: 4.8,
  walletBalance: 15400,
};

export const updateCurrentUser = (userData: any) => {
  CURRENT_USER = {
    id: `u${Date.now()}`,
    name: `${userData.firstName} ${userData.lastName}`,
    username: userData.username,
    avatar: userData.profileImageUrl || 'https://picsum.photos/seed/default/200/200',
    role: userData.userRole,
    rating: 4.8,
    walletBalance: 15400,
  };
};

export const SERVICES: Service[] = [
  {
    id: 's1',
    freelancerId: 'f1',
    freelancerName: 'Sarah J.',
    freelancerAvatar: 'https://picsum.photos/seed/sarah/200/200',
    title: 'Professional UI/UX Design for Mobile Apps',
    description: 'I will design clean, modern, and user-centric mobile app interfaces using Figma. Perfect for final year projects.',
    category: 'Design',
    price: 5000,
    priceType: 'FIXED',
    rating: 4.9,
    reviewsCount: 12,
    portfolioImages: ['https://picsum.photos/seed/ui1/400/300', 'https://picsum.photos/seed/ui2/400/300'],
    aiMatchScore: 98,
  },
  {
    id: 's2',
    freelancerId: 'f2',
    freelancerName: 'Emmanuel K.',
    freelancerAvatar: 'https://picsum.photos/seed/emmanuel/200/200',
    title: 'Laundry Service - Pick up & Delivery',
    description: 'Fast and clean laundry service for busy students. Wash, dry, and fold. Hostel pickup available.',
    category: 'Laundry',
    price: 2500,
    priceType: 'NEGOTIABLE',
    rating: 4.5,
    reviewsCount: 45,
    portfolioImages: ['https://picsum.photos/seed/laundry/400/300'],
    aiMatchScore: 85,
  },
  {
    id: 's3',
    freelancerId: 'f3',
    freelancerName: 'Chidinma O.',
    freelancerAvatar: 'https://picsum.photos/seed/chidinma/200/200',
    title: 'Portrait Photography & Headshots',
    description: 'High quality portraits for LinkedIn, CVs, or social media. 1 hour session on campus.',
    category: 'Photography',
    price: 8000,
    priceType: 'FIXED',
    rating: 5.0,
    reviewsCount: 8,
    portfolioImages: ['https://picsum.photos/seed/photo1/400/300', 'https://picsum.photos/seed/photo2/400/300'],
    aiMatchScore: 92,
  },
  {
    id: 's4',
    freelancerId: 'f4',
    freelancerName: 'Tobi A.',
    freelancerAvatar: 'https://picsum.photos/seed/tobi/200/200',
    title: 'Python & Data Analysis Tutoring',
    description: 'Struggling with CSC 201? I can help you understand Python, Pandas, and basic ML concepts.',
    category: 'Tutoring',
    price: 3000,
    priceType: 'FIXED',
    rating: 4.7,
    reviewsCount: 22,
    portfolioImages: ['https://picsum.photos/seed/code/400/300'],
    aiMatchScore: 78,
  },
  {
    id: 's5',
    freelancerId: 'f5',
    freelancerName: 'Kemi A.',
    freelancerAvatar: 'https://picsum.photos/seed/kemi/200/200',
    title: 'Academic Writing & Research Papers',
    description: 'Professional academic writing, research papers, and thesis assistance. APA/MLA formatting included.',
    category: 'Writing',
    price: 4500,
    priceType: 'NEGOTIABLE',
    rating: 4.8,
    reviewsCount: 31,
    portfolioImages: ['https://picsum.photos/seed/writing/400/300'],
    aiMatchScore: 88,
  },
  {
    id: 's6',
    freelancerId: 'f6',
    freelancerName: 'Funmi B.',
    freelancerAvatar: 'https://picsum.photos/seed/funmi/200/200',
    title: 'Hair Styling & Makeup Services',
    description: 'Professional hair styling and makeup for events, photoshoots, or special occasions. Mobile service available.',
    category: 'Beauty',
    price: 6000,
    priceType: 'FIXED',
    rating: 4.9,
    reviewsCount: 18,
    portfolioImages: ['https://picsum.photos/seed/beauty1/400/300', 'https://picsum.photos/seed/beauty2/400/300'],
    aiMatchScore: 91,
  },
  {
    id: 's7',
    freelancerId: 'f7',
    freelancerName: 'Chuka M.',
    freelancerAvatar: 'https://picsum.photos/seed/chuka/200/200',
    title: 'Web Development - React & Node.js',
    description: 'Full-stack web development using modern technologies. Perfect for capstone projects and portfolios.',
    category: 'Development',
    price: 15000,
    priceType: 'NEGOTIABLE',
    rating: 4.9,
    reviewsCount: 14,
    portfolioImages: ['https://picsum.photos/seed/web1/400/300', 'https://picsum.photos/seed/web2/400/300'],
    aiMatchScore: 95,
  },
  {
    id: 's8',
    freelancerId: 'f8',
    freelancerName: 'Adunni L.',
    freelancerAvatar: 'https://picsum.photos/seed/adunni/200/200',
    title: 'Mathematics & Statistics Tutoring',
    description: 'Expert help with Calculus, Statistics, and Mathematical Methods. Available for group sessions.',
    category: 'Tutoring',
    price: 2800,
    priceType: 'FIXED',
    rating: 4.6,
    reviewsCount: 27,
    portfolioImages: ['https://picsum.photos/seed/math/400/300'],
    aiMatchScore: 82,
  },
  {
    id: 's9',
    freelancerId: 'f9',
    freelancerName: 'Tunde O.',
    freelancerAvatar: 'https://picsum.photos/seed/tunde/200/200',
    title: 'Logo Design & Brand Identity',
    description: 'Creative logo design and complete brand identity packages. Multiple concepts and unlimited revisions.',
    category: 'Design',
    price: 7500,
    priceType: 'FIXED',
    rating: 4.8,
    reviewsCount: 19,
    portfolioImages: ['https://picsum.photos/seed/logo1/400/300', 'https://picsum.photos/seed/logo2/400/300'],
    aiMatchScore: 89,
  },
  {
    id: 's10',
    freelancerId: 'f10',
    freelancerName: 'Blessing C.',
    freelancerAvatar: 'https://picsum.photos/seed/blessing/200/200',
    title: 'Event Photography & Videography',
    description: 'Professional coverage for birthdays, graduations, and campus events. Same-day editing available.',
    category: 'Photography',
    price: 12000,
    priceType: 'NEGOTIABLE',
    rating: 4.7,
    reviewsCount: 23,
    portfolioImages: ['https://picsum.photos/seed/event1/400/300', 'https://picsum.photos/seed/event2/400/300'],
    aiMatchScore: 86,
  },
  {
    id: 's11',
    freelancerId: 'f11',
    freelancerName: 'Segun K.',
    freelancerAvatar: 'https://picsum.photos/seed/segun/200/200',
    title: 'Mobile App Development - Flutter',
    description: 'Cross-platform mobile app development using Flutter. From concept to deployment on both iOS and Android.',
    category: 'Development',
    price: 25000,
    priceType: 'NEGOTIABLE',
    rating: 4.9,
    reviewsCount: 11,
    portfolioImages: ['https://picsum.photos/seed/mobile1/400/300', 'https://picsum.photos/seed/mobile2/400/300'],
    aiMatchScore: 93,
  },
  {
    id: 's12',
    freelancerId: 'f12',
    freelancerName: 'Amara N.',
    freelancerAvatar: 'https://picsum.photos/seed/amara/200/200',
    title: 'Content Writing & Social Media',
    description: 'Engaging content creation for blogs, social media, and marketing materials. SEO-optimized writing.',
    category: 'Writing',
    price: 3500,
    priceType: 'FIXED',
    rating: 4.6,
    reviewsCount: 35,
    portfolioImages: ['https://picsum.photos/seed/content/400/300'],
    aiMatchScore: 84,
  }
];

export const CATEGORIES = [
  'All', 'Design', 'Development', 'Photography', 'Tutoring', 'Writing', 'Beauty', 'Laundry'
];

export const MOCK_TRANSACTIONS: WalletTransaction[] = [
  { id: 't1', type: 'DEPOSIT', amount: 20000, date: '2023-10-25', status: 'SUCCESS', description: 'Wallet Top-up' },
  { id: 't2', type: 'PAYMENT', amount: 5000, date: '2023-10-26', status: 'SUCCESS', description: 'Payment to Sarah J.' },
  { id: 't3', type: 'EARNING', amount: 3500, date: '2023-10-28', status: 'SUCCESS', description: 'Gig Completion: Logo Design' },
];

export const ACTIVE_JOBS: Job[] = [
  { id: 'j1', serviceId: 's1', clientId: 'u1', freelancerId: 'f1', status: 'IN_PROGRESS', amount: 5000, title: 'UI Design for Project', date: '2023-10-26' },
  { id: 'j2', serviceId: 's7', clientId: 'u1', freelancerId: 'f7', status: 'IN_PROGRESS', amount: 15000, title: 'E-commerce Website Development', date: '2023-10-28' },
  { id: 'j3', serviceId: 's11', clientId: 'u1', freelancerId: 'f11', status: 'PENDING', amount: 25000, title: 'Mobile App - Flutter Development', date: '2023-11-01' },
  { id: 'j4', serviceId: 's9', clientId: 'u1', freelancerId: 'f9', status: 'IN_PROGRESS', amount: 7500, title: 'Brand Identity & Logo Design', date: '2023-10-30' },
  { id: 'j5', serviceId: 's5', clientId: 'u1', freelancerId: 'f5', status: 'PENDING', amount: 4500, title: 'Research Paper Writing', date: '2023-11-02' },
  { id: 'j6', serviceId: 's10', clientId: 'u1', freelancerId: 'f10', status: 'IN_PROGRESS', amount: 12000, title: 'Graduation Event Photography', date: '2023-10-29' }
];